version: "3"
services:
    web:
      build: .
      ports: 
        - "3045:3000"
      depends_on:
        mongo:
          condition: service_started
    mongo:
      image: mongo
      ports:
        - "27017:27017"