version: "3"
services:
    web:
      build: .
      ports: 
        - "3046:3001"
      depends_on:
        mongo:
          condition: service_started
    mongo:
      image: mongo
      ports:
        - "27018:27017"